config/routes.rb
Rails.application.routes.draw do

  get '/' => 'home#index', as: 'home'

  get '/session/new' => 'session#new', as: 'new_session'
  post '/session' => 'session#create'
  get '/logout' => 'session#logout'

  get '/users/new' => 'users#new'
  post '/users' => 'users#create'
  get '/users/show' => 'users#show'

  get '/projects' => 'projects#index'
  get '/projects/show' => 'projects#show'
 
  get '/blogs' => 'blogs#index'
  get '/blogs/show' => 'blogs#show'

  get '/picture' => 'picture#index', as: 'picture'

end

app/models/blog.rb
class Blog < ActiveRecord::Base

  def index
    @blogs = Blog.all(updated_at: :desc)
  end

  def show
    # this is what's working for projects...
    @blog = Blog.find params[:format]
  end


end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionHelper
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.order(updated_at: :desc)
  end

  def show
    # this is what's working for projects...
    @blog = Blog.find params[:format]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/picture_controller.rb
class PictureController < ApplicationController

  def index

  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.order(status_date: :desc)
  end

  def show

    @project = Project.find params[:format]
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      login(@user)
      redirect_to home_path
    else
      redirect_to new_session_path(@user), flash: { error: "Invalid credentials, please try again." }
    end
  end

  def new
    @user = User.new
  end

  def logout
    session.delete(:user_id)
    redirect_to home_path
  end

  def login(user)
    session[:user_id] = user.id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper

  def logged_in?
    session[:user_id]
  end

  def authenticate!
    redirect_to home_path unless logged_in?
  end

end

app/views/blogs/_add_flex.html.erb
<p class="blog-text">I use a PC that runs Linux. My default browser is Chrome. I made this website in that environment and it looked okay. I'm not a design genius but the photo on my homepage made me happy every time I looked at it, my headers were at the top of the page, footer at the foot...<span style="font-style:italic">or so I thought.</span></p>

<p class="blog-text">One day I showed it to a friend who uses a Mac and - to my horror - the footer was not behaving anything like it did on my computer! The 'toggle device' option on the Chrome DevToolkit hadn't uncovered this problem. It shows how the site looks on other devices and screen sizes but not other browsers.</p>

<p class="blog-text">I'm using Bootstrap for general styling on this site. It has the standard grid structure and some other nifty things. I've used Materialize on other projects, which has similar features. I had not used Flex anywhere before but it seemed like the solution to this problem.</p>

<p class="blog-text">There's some <%= link_to "decent documentation", "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Advanced_layouts_with_flexbox", class: "content-link" %> on flex containers on the Mozilla Developer Network. I got more practical information from this <%= link_to "cheatsheet", "http://www.sketchingwithcss.com/samplechapter/cheatsheet.html", class: "content-link" %> and from <%= link_to "this series", "https://www.youtube.com/watch?v=Y8zMYaD1bz0", class: "content-link" %> of YouTube videos.</p>

<p class="blog-text">Flex box was really simple to implement. It took maybe seven minutes of copying and pasting tmy progress this afternoon on a Mac at Dev Bootcamp just to make sure.</p>

<p class="blog-text"><span style="font-style:italic">Pretend this is hours passing....</span></p>

<p class="blog-text">It worked! Looking at the site on the Macs at DBC, things seem to be where I want them. The main point of this blog is that, even now, it's not safe to assume things that look good in one environment or browser will render the way you want them to in another. Also that making your site look good across different browsers is not very difficult.</p>

app/views/blogs/_nested_forms.html.erb
<p class="blog-text">Nested forms are great! No, really, they are fantastic and definitely worth the trouble of figuring out how to make them do what you want. In this post, I'll cover the basic use-case for nested forms and show the steps to implementing them in a Rails app. Note: I'm running Rails 4.2.6 here and I've added links to relevant resources where I think they'll be useful for further reading. To build out my own app, I started with the <%= link_to "Rails guide", "http://guides.rubyonrails.org/form_helpers.html", class: "content-link" %> on forms, specifically the 'nested forms' info in section 9.</p>

<h4 class="blog-subhead">Use case</h4>
<p class="blog-text">So, when should you use nested forms? If you have two (or more) objects that have a parent-child relationship - in other words, you're not likely to create a parent object without also wanting to create the child object(s) or vice versa - that's when nesting the user input about those objects makes sense.</p>

<p class="blog-text">For example, in the website I made to capture registrations for a charity golf tournament, I created a <code>signup</code> object that contained information about the person signing up, such as name, contact information, etc. That's the parent object.</p>

<p class="blog-text">Anyone who was signing up on the website would want to do one of three things at the golf tournament: play golf, attend the dinner or sponsor some part of the event. That's three objects that could be the child of the <code>signup</code> object: <code>player</code>, <code>diner</code> and <code>sponsorship</code>. I didn't want anyone to be able to register as a player, for example, if they had not provided their name and contact information and there would be no point in giving your personal info (as a <code>signup</code>) if you didn't want to play golf, eat dinner or sponsor something. A perfect situation for nested forms.</p>

<h4 class="blog-subhead">Setting up the models</h4>
<div class="row">
  <div class="col-sm-8 col-md-8 col-lg-8">
    <p class="blog-text">When you create the nested form, the outer part will be the parent object: <code>signup</code> in my example. Since the form will be gathering information about both the parent and the child objects, the parent's model has to be able to recieve and process information for the child objects from that form. You'll use the Active Record method <code>accepts_nested_attributes_for</code> in the parent-object's model to make that happen. I group them all at the top with their Active Record associations, so I can see that I've named them correctly.</p>
  </div>

  <div class="col-sm-4 col-md-4 col-lg-4">
    <%= image_tag "signupNestedAttrib.png", class: "schema code-snapshot" %>
  </div>
</div>

<div class="row">
  <div class="col-sm-8 col-md-8 col-lg-8">
    <h4 class="blog-subhead">Changes in the controllers</h4>
  </div>
</div>

<div class="row">
  <div class="col-sm-4 col-md-4 col-lg-4">
    <%= image_tag "dinersController.png", class: "schema code-snapshot" %>
  </div>

  <div class="col-sm-8 col-md-8 col-lg-8">
    <p class="blog-text">Your controllers are going to make you new objects and to supply you with the appropriate existing objects. With nested objects, you need to make sure the controller builds the correct associations between the parent and child(ren) whenever it makes new entries in the database.</p>
  </div>
</div>

<div class="row">
  <div class="col-sm-4 col-md-4 col-lg-4">
    <%= image_tag "signupParams.png", class: "schema code-snapshot" %>
  </div>

  <div class="col-sm-8 col-md-8 col-lg-8">
    <p class="blog-text">My app has three different child objects but a user would only be making one type, not all three. To differentiate, I made my routes specific to the child objects...which means that my <code>new</code> methods are in the children's controllers rather than the parent's. This is the Diners Controller; the ones for <code>players</code> and <code>sponsorships</code> look just like this. If you had only one type of child object to construct, you would more likely put the <code>new</code> method in the Signups Controller. It just needs to make a fresh <code>signup</code> to send to the <code>form_for</code> helper.</p>

    <p class="blog-text">When your form sends the post request to the parent object's controller, it'll have parameters for the child object also. You'll specify all the whitelisted parameters of the child object along with those of the parent in the <code>signup_params</code> private method. (See <%= link_to "this section", "http://api.rubyonrails.org/classes/ActionController/Parameters.html", class: "content-link" %> of the Rails API for more info about whitelisting and why that's important/required.) It seems obvious but you should be sure to name the nested attributes to match the names you listed in the parent controller. For example, <code>players_attributes</code>, rather than <code>player_attributes</code>.</p>
  </div>
</div>


<div class="row">
  <div class="col-sm-4 col-md-4 col-lg-4">
    <%= image_tag "setSignup.png", class: "schema code-snapshot" %>
  </div>

  <div class="col-sm-8 col-md-8 col-lg-8">
    <p class="blog-text">When you take a look at how the parameters are laid out here, you'll notice that it's basically a nested array in which the <code>signup</code> parameters are at the top level (<code>:first_name</code> through <code>:id</code>) and then the various children's information follows: <code>:player_attributes</code>, <code>diners_attributes</code> and <code>sponsorship_attributes</code>, each with its list of params.</p>

    <p class="blog-text">The other thing you need to do in the controller is to set up the parent for your form to use. I used a <code>before_action</code> <%= link_to "callback", "http://guides.rubyonrails.org/action_controller_overview.html", class: "content-link" %> to run the <code>set_signup</code> private method in the signups controller. This method will supply the <code>signup</code> object to the form, whenever the controller hits the methods you include in the callback.</p>
  </div>
</div>

<h4 class="blog-subhead">Building the form</h4>
<div class="row">
  <div class="col-sm-8 col-md-8 col-lg-8">
    <p class="blog-text">There are two things Rails needs to create the nested form. One of them, obviously, is the form itself and I'll get to that shortly. First though, you need to properly associate the children objects with the parent object. That way, when your nested form saves data for the children, they'll have the parent's id already in place.</p>

    <p class="blog-text">In order to make this happen, write a helper method that uses the Active Record <code>build</code> method to create new child objects however many times you specify. I decided that users would most likely be signing up four players, two diners or one sponsorship at a time.</p>
  </div>

  <div class="col-sm-4 col-md-4 col-lg-4">
    <%= image_tag "formHelper.png", class: "schema code-snapshot" %>
  </div>
</div>

    <p class="blog-text">It's worth looking at these last two methods together. Both return a <code>signup</code> object and both ultimately use that object's info in a form. Their names are similar but they don't do exactly the same thing.

    The controller method, <code>set_signup</code> gets called when a user is going to view or change an existing <code>signup</code>. It'll find the object from the id in the params. A new <code>signup</code> won't hit this method at all.</p>

    <p class="blog-text">The <code>setup_signup</code> method in the Form Helper is called by the form itself. That means you will call this method for existing <code>signup</code> objects as well as when you're making new ones so you have to accommodate both cases. If you're creating a brand new <code>signup</code>, <code>setup_signup</code> returns the <code>signup</code> object with a bunch of associated, child objects, full of <code>nil</code> information.</p>

    <p class="blog-text">If the user is going to the <code>:show</code>, <code>:edit</code> or <code>:update</code> route, they'll hit both methods. First, <code>set_singup</code> sends their existing  <code>signup</code> to the form and then the form triggers <code>setup_signup</code>. That method returns the <code>signup</code> with its associated <code>players</code>, <code>diners</code> or a <code>sponsorship</code>.</p>

<div class="row">
  <div class="col-sm-8 col-md-8 col-lg-8">
    <p class="blog-text">The changes to the form itself are pretty simple. In line 2, you've got the <code>form_for</code> Rails helper and you pass it the <code>signup</code> object returned by the <code>setup_signup</code> method in the Form Helper. Form fields that relate to the parent object are treated in the usual way, as in lines 7 and 8.</p>

    <p class="blog-text">When you get to the fields that will supply data for the child object, you start a new section of <code>fields_for</code>, as in line 18. (The <code>diner_count</code> variable in my example has nothing to do with making a loop here. I just wanted the labels on the form to show 'Diner 1' and 'Diner 2' so I added a counter. Rails magic makes the <code>fields_for</code> loop as many times as you have <code>diner</code> objects associated with the parent <code>signup</code>.)</p>

    <p class="blog-text">The really important thing with this form is to make sure that your child object's <code>fields_for</code> stuff is properly nested in the <code>fields_for</code> element for the parent object. Line 28 is the end of the child element, then the <code>f.submit</code> for the parent and the end of the parent element is in line 34. There is no explicit <code>f.submit</code> for the child's <code>form_for</code> element.</p>

    <p class="blog-text">I decided to make separate forms, depending on which child object the user was working on. But, if you wanted to have a second child object in the same nested form, you could just put another <code>form_for</code> element between the diners element on line 28 and the <code>submit</code> button on line 31.
  </div>

  <div class="col-sm-4 col-md-4 col-lg-4">
    <%= image_tag "nestedForm.png", class: "schema code-snapshot" %>
  </div>
</div>

<p class="blog-text">And that is nested forms for a Rails app.</p>

app/views/blogs/_raspberry_pi.html.erb
<p class="blog-text">I'm just getting started on this project so this blog is currently a list of things I need to figure out to make it work. I'll fill in details as I complete each step.</p>

<p class="blog-text">This is what I have to do:</p>

<ul>
  <li>Install the raspberry pi OS on this miniSD card (they are <span style="font-style:italic">not kidding</span> with that 'mini').</li>
    <p class="blog-text">Spent the last couple of days mentoring at Dev Bootcamp so not a lot of progress...so far I've been downloading the Raspbian OS and formatting the SD card. It took a couple of attempts at downloading the operating system's zip file before I could successfully extract the files to the SD card.</p>
    
    <p class="blog-text">Once I got the SD card set up, I plugged that into its slot on the RPi, then connected the all the other hardware to the RPi: keyboard, mouse, HDMI cable. I connected the HDMI cable to my tv and then, finally, plugged in the power adapter for the RPi.</p>

    <p class="blog-text">Seeing 'Welcome to PIXEL Powered by Raspbian' on my tv screen was a nice moment. Among other things, it made me crave a larger monitor for my day-to-day computer use.</p>
    
  <li>Make the raspberry pi connect to the wifi here at home. (This looks like it'll be pretty easy, but it's a step in the process so it goes on the list.)</li>

    <p class="blog-text">As usual, 'looks easy' was...not quite an accurate assessment.</p>

    <p class="blog-text">The USB wifi dongle did detect my wifi right away but I had no real way to see that at first. I found some step-by-step instructions <%= link_to "here", "https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md", class: "content-link" %> and <%= link_to "here", "https://learn.adafruit.com/adafruits-raspberry-pi-lesson-3-network-setup/setting-up-wifi-with-occidentalis", class: "content-link" %>. As with all the other things plugged into the RPi, the wifi adapter has to be in the USB port before powering up.</p>

    <p class="blog-text">The first thing was to confirm that the RPi was detecting my wifi. From the command line, I checked that: <code>sudo iwlist wlan0 scan</code>. This gave me a list of all the local wifi networks. I live in a condo building in the city, so there were quite a few. There was a lot of data (mostly meaningless to me and, for my current purpose, extraneous) in these results but it was divided into 'channels' and my network was listed as <code>ESSID: "my network name"</code> for one of them.</p>

    <p class="blog-text">Next, I had to configure this "wlan0" with my wifi password. From the command line, I opened the 'interfaces' file: <code>sudo nano /etc/network/interfaces</code>and changed it per step 3 in the second link above. I haven't had to make any changes to my 'wpa-supplicant' file so far.</p>

  <div class="row">
    <div class="col-sm-4 col-md-4 col-lg-4">
      <%= image_tag "raspberry_cat.jpg", class: "schema code-snapshot" %>
    </div>

    <div class="col-sm-8 col-md-8 col-lg-8">
      <li>Install the camera & figure out how to trigger it to take a picture and store the image</li>

        <p class="blog-text">This one actually was easy. I went through <%= link_to "this tutorial", "https://www.raspberrypi.org/learning/getting-started-with-picamera/", class: "content-link"%> and everything worked on the very first try. Crazy. This is a picture of my cat, Edgar, wondering why I'm sitting on the floor in front of my tv and not scratching his head.</p>
     
      <li>Figure out how to interpret the image</li>
      <li>Figure out how to turn the raspberry pi into a web server</li>
      <li>Set up the website</li>
      <li>DEPLOY</li>
    </div>
</ul>

<p class="blog-text">Should be fun.</p>

app/views/blogs/_rspec_test_rails.html.erb
<p class="blog-text">Testing is super important! Everyone knows this and I really, seriously enjoy writing tests. I like figuring out what I should test and how to break down my app into pieces that I can test individually. In spite of these facts, I had not actually written very many tests for my Ruby on Rails apps. Then I thought, 'Hey, THIS is a Rails app! I'll write a bunch of tests for my own website, make sure I know how to test all the different aspects of the app and I'll document it all in a blog." (This is the blog part of that plan.)</p>

<p class="blog-text">The first thing I realized was that the minitest suite that Rails generated automatically is not the same as the Rspec test suite I'm used to. There was already a group in my gem file for gems that should apply for the development and test environments, so I added <code>gem "rspec-rails"</code> to that group and did a fresh <code>bundle install</code>. Then I ran <code>rails generate rspec:install</code> and Rails created a spec folder and a couple of helper files.</p>

<p class="blog-text">(This blog post is in process. I'm updating it as I work through the testing on my site.)</p>

app/views/blogs/index.html.erb
<div class="carousel">
  <div class="content-list">
    <% @blogs.each do |blog| %>
      <div class="project row">
        <div class= "project-image col-xs-2 col-sm-2 col-md-2 col-lg-2">
          <%= image_tag("#{blog.screenshot}", class: "image-#{blog.screenshot_orientation}") %>
        </div>
        <div class="project-info col-xs-10 col-sm-10 col-md-10 col-lg-10" >
          <h2><%= link_to "#{blog.title}", blogs_show_path(blog), class: "content-link"  %></h2>
          <p><%= blog.subtitle %></p>
          <p class="blog-date"><%= blog.written_date.strftime("%B %d, %Y") %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="project-specifics">
  <h2  class="blog-title"><%= @blog.title %></h2>
  <h3><%= @blog.subtitle %></h3>
  <h4 style="font-style: italic"><%= @blog.written_date.strftime("%B %d, %Y") %></h4>

  <%= render partial: "#{@blog.page_reference}" %>
</div>

app/views/home/index.html.erb
<div class="home-background">
  <h1 class="name">Heather Conklin, CFP</h1>
  <div class="info flex-container">
    <div class="box flex-body">
      <p class="bio">I'm a web developer who enjoys the mental rewards of writing beautiful, functional code.</p>
      <p class="bio">I get to create websites from scratch and figure out how to make them work while making the users' experience as smooth as possible.</p>
      <!-- <p class="bio">In my previous career as a personal financial planner, I assisted individuals and families in reaching their short- and long-term economic goals. My background gave me experience in asking deep questions, producing thorough analyses of complex problems and providing comprehensible explanations and context of technical issues for laypeople. It turns out these skills translate well to a career in technology and web development.</p> -->
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heatherconklin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>

<header>
  <div class="container-fluid nav-bar">
    <div class="row">
      <div class="col-lg-2 col-lg-offset-1 col-md-2 col-md-offset-1 col-sm-2 col-sm-offset-1"><%= link_to "HOME", home_path, class: "pull-center nav-link" %></div>
      <div class="col-lg-2 col-md-2 col-sm-2"><%= link_to "BLOGS", blogs_path, class: "pull-center nav-link" %></div>
      <div class="col-lg-2 col-md-2 col-sm-2"><%= link_to "PROJECTS", projects_path, class: "pull-center nav-link" %></div>
      <div class="col-lg-1 col-lg-offset-1 col-md-1 col-md-offset-1 col-sm-1 col-sm-offset-1"><%= link_to image_tag("GitHub-Mark-Light-32px.png"), "https://github.com/heath3conk", class:"valign pull-right nav-link" %></div>
      <div class="col-lg-1 col-md-1 col-sm-1"><%= link_to image_tag("In-White-28px-R.png"), "https://www.linkedin.com/in/heathercconklin", class: "valign pull-left nav-link"%></div>
      <div class="col-lg-1 col-md-1 col-sm-1"><%= link_to image_tag("technology.svg"), new_session_path, class:"valign pull-right nav-link" %></div>
              </div>
    </div>
  </div>
</header>  

<main>
  <body>
    <div class="body-wrapper">
      <div class="flex-container">
        <div class="box flex-body">
          <%= yield %>
        </div>

        <div class="box flex-foot">
          <footer>
            <div class="container-fluid footer-bar">
              <div class="row">
                <div class="col-lg-12 text-center"><%= link_to "RESUME", asset_path("Resume.pdf"), class: "foot-link" %></div>
              </div>
              <div class="row">
                <div class="col-lg-12 text-center"><%= link_to "EMAIL ME", "mailto:heath3conk@gmail.com", class: "foot-link" %></div>
              </div>
              <div class="row">
                <div class="col-lg-12 text-center"><%= link_to "THIS GREAT PICTURE", picture_path, class: "foot-link" %></div>
              </div>

              <div class="row">
                
            </div>
          </footer>
        </div>
      </div>
    </div>

  </body>
</main>
</html>

app/views/picture/index.html.erb
<div class="home-background">
  
  <div class="info picture-info flex-container">
    <div class="box flex-body">
      <p class="bio">This is my maternal grandmother and her sisters. Based on their apparent ages, it must have been taken in the late 1920s or early 1930s. When I got the digital copy, it was labeled "Fourth of July Parade" by my grandmother herself, as far as I know.</p>

      <p class="bio">My grandmother was the oldest of the four, so she's the one with the rocket(!), which seems to have a rudder(?)</p>

      <p class="bio">That side of the family were "makers" long before that was even a thing. Thanks for the inspiration, family.</p>
    </div>
</div>

app/views/projects/_katz_golf.html.erb
<div class="project-content">
  <div class="row">
    <div class="col-sm-8 col-md-8 col-lg-8">
      <p>I created a website to manage registrations for the Christopher J. Katzenstein 7th Annual Memorial Golf Tournament, which took place on September 17, 2016. Participants can register to play, attend the dinner or sponsor the event. I deployed the site on Heroku (so there's a long load time if it's sleeping) and the organizers got the URL from GoDaddy and directed it there.</p>
      <p><%= link_to "www.ckatzgolf.com", "www.ckatzgolf.com", class: "content-link" %></p>
      <p>This is, in general, a pretty straightforward app. There's a user model so the organizers can login and view signup information. This schema illustrates the relationships among the models related to the registrations.</p>

      <p>I nested the specific type of registration under the general model "signup" so that I'd have one place to gather the registrant's name and contact information that was common to all. I created a nested form and used the nav-bar links to generate the correct fields for the child-model (player, diner or sponsorship). Please see <%= link_to "my blog about nested forms", "/blogs/show.1", class: "content-link" %> for more details about how that works with Rails.</p>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
      <%= image_tag "katz_golf_schema.png", class: "schema" %>
    </div>
  </div>
</div>

app/views/projects/_voter_bloc.html.erb
<h2>Voter Bloc</h2>

app/views/projects/index.html.erb
 <div class="carousel"> 
  <div class="content-list">
    <% @projects.each do | project | %>
      <div class="project row">
        <div class="project-image col-xs-2 col-sm-2 col-md-2 col-lg-2">
          <%= image_tag("#{project.screenshot}", class: "image-#{project.screenshot_orientation}") %>
        </div>
        <div class="project-info col-xs-10 col-sm-10 col-md-10 col-lg-10" >
          <h2><%= link_to "#{project.title}", projects_show_path(project), class: "content-link"  %></h2>
          <p><%= project.short_description %></p>
          <p><%= project.technologies %></p>
          <p><%= link_to "#{project.repo}", "#{project.repo}", class: "content-link" %></p>
        </div>

      </div>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="project-specifics">
  <h2><%= @project.title %></h2>
  <h3><%= link_to "#{@project.repo}", "#{@project.repo}", class: "content-link" %></h3>
  <h3><span style="font-weight:bold">Primary technologies used: </span><%= @project.technologies %></h3>

  <%= render partial: "#{@project.page_reference}" %>
</div>

app/views/session/new.html.erb
<h2 class="name">I haven't built this functionality yet so don't try to login or you'll get an error.</h2>
<h2 class="name">Also, don't try to login once I have built it. This isn't your website.</h2>

<div class="container signup-form">
  <%= form_for :session, url: session_path(@user) do |f| %>
    <% if flash[:error] %>
      <div class="error-explanation">
        <p class="error"><%= flash[:error] %></p>
      </div>
    <% end %>

    <div class="user-action">
      <%= f.label :username, "Username", class: "form-label" %><br>
      <%= f.text_field :username %>

      <%= f.label :password, "Password", class: "form-label" %><br>
      <%= f.password_field :password %>

      <%= f.label :email, "Email", class: "form-label" %><br>
      <%= f.text_field :email %>

      <%= f.label :role, "Role", class: "form-label" %><br>
      <%= f.text_field :role %>

      <div class="actions waves-effect waves-light btn-large players-signup-button">
        <%= f.submit "Login" %>
      </div>
    </div>

  <% end %>
</div>